
package frames;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.Timer;

import JDialogs.JDVehicleRegister;
import JDialogs.jDConductorRegister;
import JDialogs.jDEditPriceTicket;
import JDialogs.jDLogin;
import JDialogs.jDPacks;
import JDialogs.jDPacksReporteDiario;
import JDialogs.jDPrivateTravels;
import JDialogs.jDReporteDiario;
import JDialogs.jDUserRegister;

/**
 *
 * @author marcos
 */
public class jfMain extends javax.swing.JFrame {

    /**
     * Método que devuelve el separador de archivos dependiendo el sistema operativo
     * 
     *
     * @return String con el separador de archivos dependiendo el sistema operativo
     */

    public static String getSeparador() {
        String separador = File.pathSeparator; // obtenemos ";" o ":"
        if (separador.equals(";")) { // si es Windows
            separador = "/";
        }
        if (separador.equals(":")) { // Si es mac o linux
            separador = "\\";
        }
        return separador;
    }

    /**
     * Creates new form jfMain
     */
    public jfMain() {
        initComponents();
        try {
            Image icon = Toolkit.getDefaultToolkit()
                    .getImage(getClass().getResource(getSeparador() + "Imagenes" + getSeparador() + "LogoTicket.png"));
            setIconImage(icon);
        } catch (Exception e) {
            System.out.println("No se encontro imagen");
        }
        new Thread(new Hilo()).start();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMFile = new javax.swing.JMenu();
        jmiLogIn = new javax.swing.JMenuItem();
        jmiLogOut = new javax.swing.JMenuItem();
        jmiRegisterUser = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jMbuyTicket = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMpack = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMReport = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMOthers = new javax.swing.JMenu();
        jmiRegistriConductores = new javax.swing.JMenuItem();
        jmRegsUniTrans = new javax.swing.JMenuItem();
        jmiEditPrices = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de venta Transporte de antorcha \"Región mixteca\"");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(java.awt.SystemColor.windowBorder);

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 51));
        lblFecha.setText("Fecha");

        lblHora.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 0, 51));
        lblHora.setText("Hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 953,
                                        Short.MAX_VALUE)
                                .addComponent(lblFecha)
                                .addGap(22, 22, 22)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblFecha)
                                        .addComponent(lblHora))
                                .addContainerGap()));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        jMFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder.png"))); // NOI18N
        jMFile.setText("Archivo");

        jmiLogIn.setAccelerator(
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmiLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/connect.png"))); // NOI18N
        jmiLogIn.setText("Iniciar Sesión");
        jmiLogIn.setToolTipText("Iniciar sesión para acceder a las herramientas del sistema");
        jmiLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogInActionPerformed(evt);
            }
        });
        jMFile.add(jmiLogIn);

        jmiLogOut.setAccelerator(
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmiLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disconnect.png"))); // NOI18N
        jmiLogOut.setText("Cerrar Sesión");
        jmiLogOut.setToolTipText("Cerrar acceso a las herramientas del sistema");
        jmiLogOut.setEnabled(false);
        jmiLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOutActionPerformed(evt);
            }
        });
        jMFile.add(jmiLogOut);

        jmiRegisterUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/report_user.png"))); // NOI18N
        jmiRegisterUser.setText("Registro de usuarios");
        jmiRegisterUser.setToolTipText("Registrar, editar, eliminar usuarios");
        jmiRegisterUser.setEnabled(false);
        jmiRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegisterUserActionPerformed(evt);
            }
        });
        jMFile.add(jmiRegisterUser);

        jmiExit.setAccelerator(
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cross.png"))); // NOI18N
        jmiExit.setText("Salir");
        jmiExit.setToolTipText("Salir del sistema");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMFile.add(jmiExit);

        jMenuBar1.add(jMFile);

        jMbuyTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money_dollar.png"))); // NOI18N
        jMbuyTicket.setText("Venta de Boletos");
        jMbuyTicket.setEnabled(false);

        jMenuItem7.setAccelerator(
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N
        jMenuItem7.setText("Generar/Cancelar Venta");
        jMenuItem7.setToolTipText("Generar una nueva venta, disponiblidad de asientos.");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMbuyTicket.add(jMenuItem7);

        jMenuItem3.setAccelerator(
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coins.png"))); // NOI18N
        jMenuItem3.setText("Generar/Cancelar Venta Privada/Especial");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMbuyTicket.add(jMenuItem3);

        jMenuBar1.add(jMbuyTicket);

        jMpack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/application_form.png"))); // NOI18N
        jMpack.setText("Paqueteria");
        jMpack.setEnabled(false);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/page_edit.png"))); // NOI18N
        jMenuItem2.setText("Generar Registro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMpack.add(jMenuItem2);

        jMenuBar1.add(jMpack);

        jMReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/report.png"))); // NOI18N
        jMReport.setText("Reportes");
        jMReport.setEnabled(false);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/database_save.png"))); // NOI18N
        jMenuItem1.setText("Reportes de Venta de boletos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMReport.add(jMenuItem1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disk.png"))); // NOI18N
        jMenuItem4.setText("Reportes de Registro de Paquetería");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMReport.add(jMenuItem4);

        jMenuBar1.add(jMReport);

        jMOthers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cog.png"))); // NOI18N
        jMOthers.setText("Otros");
        jMOthers.setEnabled(false);

        jmiRegistriConductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/report_user.png"))); // NOI18N
        jmiRegistriConductores.setText("Registro de conductores");
        jmiRegistriConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistriConductoresActionPerformed(evt);
            }
        });
        jMOthers.add(jmiRegistriConductores);

        jmRegsUniTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/report_magnify.png"))); // NOI18N
        jmRegsUniTrans.setText("Registro de Unidades de transporte");
        jmRegsUniTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegsUniTransActionPerformed(evt);
            }
        });
        jMOthers.add(jmRegsUniTrans);

        jmiEditPrices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coins_add.png"))); // NOI18N
        jmiEditPrices.setText("Editar Precios");
        jmiEditPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditPricesActionPerformed(evt);
            }
        });
        jMOthers.add(jmiEditPrices);

        jMenuBar1.add(jMOthers);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLogInActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiLogInActionPerformed
        JDialogs.jDLogin Log_In = new jDLogin(this, rootPaneCheckingEnabled);
        Log_In.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jmiLogInActionPerformed

    private void jmiRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiRegisterUserActionPerformed
        JDialogs.jDUserRegister User_Register = new jDUserRegister(this, rootPaneCheckingEnabled);
        User_Register.setVisible(true);

    }// GEN-LAST:event_jmiRegisterUserActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiExitActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "¿Usted está seguro de salir?", "Saliendo...",
                JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (res == 0) {
            System.exit(0);
        }
    }// GEN-LAST:event_jmiExitActionPerformed

    private void jmiLogOutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiLogOutActionPerformed
        jfMain cerrar = new jfMain();
        cerrar.setVisible(true);
        jmiLogIn.setEnabled(true);
        this.dispose();
    }// GEN-LAST:event_jmiLogOutActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        JDialogs.jDPacks paqueteria = new jDPacks(this, rootPaneCheckingEnabled);
        paqueteria.show();
    }// GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem7ActionPerformed
        JDialogs.jDticketsBuy ventadeBoletos = new JDialogs.jDticketsBuy(this, rootPaneCheckingEnabled);
        ventadeBoletos.setVisible(true);
    }// GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        jDReporteDiario reportDay = new jDReporteDiario(null, rootPaneCheckingEnabled);
        reportDay.show();
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiRegistriConductoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiRegistriConductoresActionPerformed
        jDConductorRegister condres = new jDConductorRegister(null, rootPaneCheckingEnabled);
        condres.show();
    }// GEN-LAST:event_jmiRegistriConductoresActionPerformed

    private void jmRegsUniTransActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmRegsUniTransActionPerformed
        JDVehicleRegister RegistroDevehiculos = new JDVehicleRegister(null, rootPaneCheckingEnabled);
        RegistroDevehiculos.show();
    }// GEN-LAST:event_jmRegsUniTransActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
        jDPrivateTravels viajesPrivados = new jDPrivateTravels(null, rootPaneCheckingEnabled);
        viajesPrivados.show();
    }// GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem4ActionPerformed
        jDPacksReporteDiario reporteDiarioPaq = new jDPacksReporteDiario(null, rootPaneCheckingEnabled);
        reporteDiarioPaq.show();
    }// GEN-LAST:event_jMenuItem4ActionPerformed

    private void jmiEditPricesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiEditPricesActionPerformed
        jDEditPriceTicket editarPrecios = new jDEditPriceTicket(null, rootPaneCheckingEnabled);
        editarPrecios.show();
    }// GEN-LAST:event_jmiEditPricesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMFile;
    public javax.swing.JMenu jMOthers;
    public javax.swing.JMenu jMReport;
    public javax.swing.JMenu jMbuyTicket;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    public javax.swing.JMenu jMpack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jmRegsUniTrans;
    public javax.swing.JMenuItem jmiEditPrices;
    public javax.swing.JMenuItem jmiExit;
    public javax.swing.JMenuItem jmiLogIn;
    public javax.swing.JMenuItem jmiLogOut;
    public javax.swing.JMenuItem jmiRegisterUser;
    private javax.swing.JMenuItem jmiRegistriConductores;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;

    // End of variables declaration//GEN-END:variables
    public class Hilo implements Runnable {

        @Override
        public void run() {
            new Timer(0, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    Date d = new Date();
                    // SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                    SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss aaaa");
                    SimpleDateFormat s1 = new SimpleDateFormat("dd/MM/yyyy");
                    lblHora.setText(s.format(d));
                    lblFecha.setText(s1.format(d));

                }
            }).start();
        }

    }

}
